export  const ActionTypes = {
    SET_BREWERIES: "SET_BREWERIES",
    SELECTED_BREWERY: "SELECTED_BREWERY",
    SET_STATE_BREWERIES: "SET_STATE_BREWERIES",
    REMOVE_SELECTED_BREWERY: "REMOVE_SELECTED_BREWERY",
}